# Generated by Django 5.1.2 on 2024-10-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=100)),
                ('round_number', models.IntegerField(default=1)),
                ('points_home', models.IntegerField(default=0)),
                ('points_away', models.IntegerField(default=0)),
                ('man_of_the_match', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
